version: '3.8'

volumes:
  # for persistence between restarts
  postgres_data: {}
  elasticsearch-data:
    driver: local
networks:
  elastic:
    driver: bridge

services:
  db:
    image: mdillon/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=targets_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5656

  web:
    build: ./services/web
    command: python run.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.8.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
